/**
 * Emits docs/FIGMA_COVERAGE.md — the coverage matrix.
 *
 * Every pixel-bearing Figma node must be accounted for by exactly one of:
 *
 *   MAPPED    an implemented component renders it, verified against the PNG
 *   PARTIAL   implemented but known to differ from the render
 *   MISSING   nothing renders it
 *   N/A       explicitly out of scope, with the reason recorded
 *
 * Default status is MISSING. Nothing is promoted without evidence, because a
 * matrix that defaults to "done" is a matrix that lies.
 *
 *   node figma/coverage.mjs > docs/FIGMA_COVERAGE.md
 */
import { execFileSync } from 'node:child_process';

const auditJson = execFileSync(
  'node',
  [new URL('./audit.mjs', import.meta.url).pathname.slice(1), '--json'],
  {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  }
);
const report = JSON.parse(auditJson);

/**
 * Claims are asserted here explicitly, per frame region. A region only leaves
 * MISSING when a named component renders it AND it has been compared to the
 * PNG. `verified` means compared against figma/frames/*.png, not "it compiles".
 */
const CLAIMS = {
  // Keyed by node ID, never by name: three frames share the name
  // "View Standards" and are three DIFFERENT screens. Keying by name is how
  // they were mistaken for duplicates in the first place.
  '2190:5138': [
    [
      'Sticky nav + links + Registry button',
      'SiteHeader.tsx',
      'PARTIAL',
      'logo is text, not the 13-path vector wordmark',
    ],
    ['Hero chip / title / lead', 'PageHeading.tsx', 'PARTIAL', 'chip missing its brand-mark icon'],
    [
      'Standard row x4',
      'StandardCard.tsx',
      'PARTIAL',
      'per-standard icon rendered as a plain disc; 84 vectors unmapped',
    ],
    [
      'Footer + newsletter + legal row',
      'SiteFooter.tsx, NewsletterForm.tsx',
      'PARTIAL',
      'logo vector unmapped',
    ],
    [
      'Back to Top rail',
      'BackToTop.tsx',
      'PARTIAL',
      'arrow is hand-drawn, not the extracted vector',
    ],
    [
      'NOISE grain overlay',
      '-',
      'MISSING',
      'Figma NOISE has no CSS equivalent; needs a tiled asset',
    ],
  ],
  '2190:851': [
    ['Sticky nav', 'SiteHeader.tsx', 'PARTIAL', 'logo vector'],
    ['Hero chip / title / lead', 'PageHeading.tsx', 'PARTIAL', 'chip icon'],
    ['Sidebar search field', 'DocumentSearch.tsx', 'MAPPED', ''],
    [
      'Sidebar version panel (closed)',
      'VersionPanel.tsx',
      'PARTIAL',
      'design is a dropdown with chevron, not a static panel',
    ],
    ['Sidebar table of contents', 'TableOfContents.tsx', 'MAPPED', ''],
    [
      'Numbered section + divider',
      'DocumentBody.tsx',
      'PARTIAL',
      'missing 40x40 circular anchor button per heading',
    ],
    [
      'Body blocks',
      'BlockRenderer.tsx',
      'PARTIAL',
      'math is unrendered source; KaTeX not installed',
    ],
    ['Footer + Back to Top', 'SiteFooter.tsx, BackToTop.tsx', 'PARTIAL', 'logo + arrow vectors'],
  ],
  '2190:1073': [
    [
      'Version dropdown OPEN',
      '-',
      'MISSING',
      '312x246 control; 296x152 popup, 2 rows, active row #fcf4f5',
    ],
    ['Nav sub-menu OPEN', 'SiteHeader.tsx', 'MAPPED', ''],
    ['All shared chrome', 'layout components', 'PARTIAL', 'inherits the 2190:851 gaps'],
  ],
  '2190:1310': [
    ['Version dropdown OPEN', '-', 'MISSING', 'as 2190:1073'],
    ['"Get Started as a Buyer" CTA', '-', 'MISSING', '48/500 heading + supporting copy'],
    ['Contact form (Full Name* field set)', '-', 'MISSING', '24/400 labels, #f8e9ea fields'],
    ['All shared chrome', 'layout components', 'PARTIAL', 'inherits the 2190:851 gaps'],
  ],
};

const STATUS_ORDER = { MISSING: 0, PARTIAL: 1, MAPPED: 2, 'N/A': 3 };

const rows = [];
for (const frame of report) {
  const claims = CLAIMS[frame.id] ?? [];
  for (const [region, impl, status, note] of claims) {
    rows.push({ frame: `${frame.name} ${frame.id}`, id: frame.id, region, impl, status, note });
  }
}
rows.sort(
  (a, b) => STATUS_ORDER[a.status] - STATUS_ORDER[b.status] || a.frame.localeCompare(b.frame)
);

const tally = rows.reduce((acc, r) => ({ ...acc, [r.status]: (acc[r.status] ?? 0) + 1 }), {});
const totals = report.reduce(
  (acc, f) => ({
    pixelBearing: acc.pixelBearing + f.counts.pixelBearing,
    text: acc.text + f.counts.text,
    vector: acc.vector + f.counts.vector,
    instance: acc.instance + f.counts.instance,
  }),
  { pixelBearing: 0, text: 0, vector: 0, instance: 0 }
);

const out = [];
out.push('# Figma Coverage Matrix');
out.push('');
out.push(
  'Generated by `node figma/coverage.mjs`. Do not hand-edit — change `CLAIMS` in that file.'
);
out.push('');
out.push(
  '**Precedence when artifacts disagree:** `frames/*.png` > `file.json` > `styles.json` > `design-tokens.json`.'
);
out.push('The PNG is the actual visual output; the extract is a lossy summary that already lost');
out.push('`fontPostScriptName`, italic, and `textDecoration` once.');
out.push('');
out.push('## Frame inventory');
out.push('');
out.push('| Frame | Node ID | Size | Pixel-bearing | Text | Vector | Instances | Type styles |');
out.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
for (const f of report) {
  out.push(
    `| ${f.name} | \`${f.id}\` | ${f.size} | ${f.counts.pixelBearing} | ${f.counts.text} | ` +
      `${f.counts.vector} | ${f.counts.instance} | ${f.typography.length} |`
  );
}
out.push('');
out.push(
  `**Totals:** ${totals.pixelBearing} pixel-bearing nodes · ${totals.text} text · ` +
    `${totals.vector} vector · ${totals.instance} instances across ${report.length} distinct frames.`
);
out.push('');
out.push('## Region coverage');
out.push('');
out.push(
  `MISSING **${tally.MISSING ?? 0}** · PARTIAL **${tally.PARTIAL ?? 0}** · MAPPED **${tally.MAPPED ?? 0}**`
);
out.push('');
out.push('| Status | Frame | Region | Implementation | Known difference |');
out.push('| --- | --- | --- | --- | --- |');
for (const r of rows) {
  out.push(`| ${r.status} | ${r.frame} | ${r.region} | ${r.impl} | ${r.note || '—'} |`);
}
out.push('');
out.push('## Typography — every distinct style, by PostScript name');
out.push('');
out.push('| Count | PostScript name | Size/Leading | Style | Decoration | Align |');
out.push('| --- | --- | --- | --- | --- | --- |');
const typeSeen = new Map();
for (const f of report) {
  for (const t of f.typography) {
    typeSeen.set(t.key, (typeSeen.get(t.key) ?? 0) + t.count);
  }
}
for (const [key, count] of [...typeSeen.entries()].sort((a, b) => b[1] - a[1])) {
  const [ps, size, style, decoration, , align] = key.split(' · ');
  out.push(
    `| ${count} | \`${ps}\` | ${size} | ${style} | ${decoration} | ${align.replace('align=', '')} |`
  );
}
out.push('');
out.push('## Strokes — every colour and weight');
out.push('');
out.push('| Count | Stroke |');
out.push('| --- | --- |');
const strokeSeen = new Map();
for (const f of report) {
  for (const s of f.strokes) strokeSeen.set(s.key, (strokeSeen.get(s.key) ?? 0) + s.count);
}
for (const [key, count] of [...strokeSeen.entries()].sort((a, b) => b[1] - a[1])) {
  out.push(`| ${count} | \`${key}\` |`);
}
out.push('');
out.push('## Stop condition');
out.push('');
out.push(
  'Work is complete only when every row above reads MAPPED and the difference report is empty.'
);
out.push('`MISSING` and `PARTIAL` counts above are the authoritative remaining-work figure.');
out.push('');

console.log(out.join('\n'));
